name: Build Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21' # Use Java version 21
        distribution: 'adopt' # Specify AdoptOpenJDK distribution

    - name: Build with Gradle
      run: gradlew.bat build
