name: Build Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Run on both Ubuntu and Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or your preferred version

    - name: Build with Gradle
      run: ${{ matrix.os == 'ubuntu-latest' && 'chmod +x gradlew &&' }} ./gradlew build || gradlew.bat build
