name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Initialize Gradle Build
      run: ./gradlew.bat init  # Use 'gradlew.bat init' for Windows

    - name: Build with Gradle
      run: .\gradlew.bat build
